### ISSUE TITLE
Improve README.md (add gif to file) on react-game

### ISSUE THREAD

**Issue by nianokia** [nianokia/techtonica-assignments#7]
### Improve README.md

Add the demo.gif from src/pictures to the README.

Add extra styling to README.md, if you see room for improvement.

[https://github.com/nianokia/techtonica-assignments/blob/main/react-game/README.md](url)

![demo](https://github.com/user-attachments/assets/a4e7117a-4b7a-4a3d-987e-5b1640fcbb81)

**Comment by MBHunter88** [comment]
Hi Nia,

I'm interested in working on this issue because I've recently been able to successfully add a gif to my README.md. I've read through the issue and understand the requirements, so I am confident I can tackle this issue. Could you please assign this to me? 

If there’s any additional information I should know or if you have any guidance, I’d appreciate it!

Thank you!

MJ

**Comment by nianokia** [comment]
It's yours!
